name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - dev

env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  AWS_REGION: "us-east-1"
  APP_NAME: "mavf-app"
  CLUSTER_NAME: "mavf-ecs-cluster"
  REPOSITORY_NAME: "mavf/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install
      working-directory: ./app

    - name: Lint App
      run: npm run lint
      working-directory: ./app

    - name: Test App
      run: npm run test
      working-directory: ./app

  ci-terraform:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.12.2"

    - name: Terraform get vars
      run: |
        chmod +x ./scripts/get_tf_vars.sh
        ./scripts/get_tf_vars.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ env.AWS_REGION }}
        S3_TF_BACKEND_URI: ${{ secrets.S3_TF_BACKEND_URI }}
        S3_TF_TERRAFORM_URI: ${{ secrets.S3_TF_TERRAFORM_URI }}

    - name: Terraform fmt check
      run: terraform fmt --recursive --check
      working-directory: ./terraform

    - name: Terraform Init
      run: terraform init -backend-config=environment/${GITHUB_REF_NAME}/backend.tfvars
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ env.AWS_REGION }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ env.AWS_REGION }}